apiVersion: v1
kind: ConfigMap
metadata:
  name: back-end-config
  namespace: detourpilot
  labels:
    app.kubernetes.io/part-of: detourpilot
    app.kubernetes.io/component: back-end
data:
  PORT: "7651"
  DEV_MODE: "false"
  RANKING_FILE: data/ranking.json
  TRIP_FILE: data/trips.json
  PLACE_FILE: data/places.json
  JWT_TTL_HOURS: "168"
